### ISSUE TITLE
Compile fail on Linux

### ISSUE THREAD

**Issue by liberodark** [collinsmith/riiablo#61] opened 2019-10-13 09:54 UTC
Hi,

Im on arch and have make this : 

chmod +x gradlew
./gradlew

But have error : 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Im try to compile for desktop only

**Comment by mysterywave** [comment] 2019-10-18 01:20
I have this problem too

**Comment by collinsmith** [comment] 2019-10-19 09:07
Duplicate of #6

**Closed by collinsmith** 2019-10-19 09:07 UTC
