### ISSUE TITLE
[Create Character Failed] NullPointerException occurred 

### ISSUE THREAD

**Issue by sunneo** [collinsmith/riiablo#126] opened 2020-11-14 14:18 UTC
Riiablo.charData.getStats().get(Stat.gold).asInt()  <- this will returns null and triggers NullPointerException
because it would returns null while getting status upon creating new character.

**Comment by collinsmith** [comment] 2020-11-14 20:24
Duplicate of #37

**Closed by collinsmith** 2020-11-14 20:24 UTC
