### ISSUE TITLE
Guide of how to compile this project and eviorment settings 

### ISSUE THREAD

**Issue by lomatus** [collinsmith/riiablo#60] opened 2019-09-24 07:32 UTC
I'm a d2 funs and exited to see this project and thanks for your selfless work.
I have try to  complie this project wihout success, the problem are all related to LibGDX eviorment.
Could you provide a guide document for beginner please.

**Comment by liberodark** [comment] 2019-10-12 09:09
Yes is not same for me but no have see how to compile on linux

**Comment by SomeFire** [comment] 2019-10-16 20:11
I use IDEA, and it runs `DesktopLauncher` successfully on 113d765d commit.

**Comment by collinsmith** [comment] 2019-10-19 09:07
Duplicate of #6

**Closed by collinsmith** 2019-10-19 09:07 UTC
